/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package invoice_automation;

import com.google.gson.Gson;
import com.intuit.ipp.data.Customer;
import com.intuit.ipp.data.Invoice;
import com.intuit.ipp.data.ReferenceType;
import com.intuit.ipp.exception.FMSException;
import com.intuit.ipp.services.DataService;
import com.intuit.ipp.services.QueryResult;
import invoice_automation.module.QuickBooksModule;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.List;

public class App {
    private static final String O_AUTH_KEYS_PATH = "app/src/main/resources/oauth_keys.json";
    public DataService dataService;

    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        OAuthKeys oAuthKeys = gson.fromJson(new FileReader(O_AUTH_KEYS_PATH), OAuthKeys.class);
        QuickBooksModule quickBooksModule = new QuickBooksModule(
                oAuthKeys.getAccessToken(),
                oAuthKeys.getRealmId(),
                true
        );
        List<Customer> customers = quickBooksModule.getAllCustomers();
        for (Customer c: customers) {
            System.out.println(c.getDisplayName());
        }
        try {
            Invoice invoice = quickBooksModule.getTestInvoice();
            quickBooksModule.sendInvoice(invoice);
        } catch (FMSException e) {
            throw new RuntimeException(e);
        }
    }
}
