/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package invoice_automation;

import com.google.gson.Gson;
import com.intuit.ipp.data.Invoice;
import invoice_automation.model.Address;
import invoice_automation.model.Conference;
import invoice_automation.model.InvoiceType;
import invoice_automation.model.PaymentMethod;
import invoice_automation.model.Registration;
import invoice_automation.model.School;
import invoice_automation.module.QuickBooksModule;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

public class App {
    private static final String O_AUTH_KEYS_PATH = "app/src/main/resources/oauth_keys.json";

    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        OAuthKeys oAuthKeys = gson.fromJson(new FileReader(O_AUTH_KEYS_PATH), OAuthKeys.class);
        QuickBooksModule quickBooksModule = new QuickBooksModule(
                oAuthKeys.getAccessToken(),
                oAuthKeys.getRealmId(),
                true
        );

        Address address = new Address("", "", "", "", "", "");

        School school = School.builder()
                .schoolName("BMUN")
                .email("")
                .phoneNumbers(List.of())
                .address(address)
                .build();

        Registration registration = Registration.builder()
                .school(school)
                .numDelegates(10)
                .conference(Conference.FC)
                .registrationDate(LocalDate.of(2023, 9, 4))
                .paymentMethod(PaymentMethod.CARD)
                .build();

        Map<InvoiceType, Invoice> map = quickBooksModule.createInvoicesFromRegistration(registration);
        System.out.println(map);
    }
}
